###########
# site.title, site.author.name

title:  Strange Case of Dr. Jekyll and Mr. Hyde
author:
  name: Robert Louis Stevenson



## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: /jekyll-gutenberg-theme
url:  'http://henrythemes.github.io/jekyll-gutenberg-theme'


########
# more settings

collections:
  chapters:
      output: false

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded


exclude:
- README.md


safe: true
lsi: false
